// Mocks generated by Mockito 5.4.6 from annotations
// in gymbuddy/test/log_activity_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gymbuddy/service/planner_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlannerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlannerService extends _i1.Mock implements _i2.PlannerService {
  MockPlannerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i4.Future<Map<String, dynamic>> fetchWorkoutLogs(
    int? year,
    int? month, {
    String? weekStart,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchWorkoutLogs,
              [year, month],
              {#weekStart: weekStart},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> completeLog(int? planId, String? description) =>
      (super.noSuchMethod(
            Invocation.method(#completeLog, [planId, description]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<dynamic>> searchExercises(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchExercises, [query]),
            returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i4.Future<List<dynamic>>);
}
